trigger:
- none

variables:
  tag: '$(Build.BuildId)'
  

stages:
  - stage: Build
    displayName: Build and Push Docker image
    jobs:
     - job: Build
       displayName: Build job
       pool: 
         vmImage: 'ubuntu-latest'
       steps:
         # Task-1: Build Docker Image and push to Azure Container Registry ACR
         - task: Docker@2
           inputs:
             containerRegistry: 'docker-svc-conn'   # Your ACR service connection name
             repository: 'app'                # Use ACR repository name
             command: 'buildAndPush'
             dockerfile: '**/Dockerfile'            # Ensure the correct path to your Dockerfile
             tags: 
               $(tag)                              # Use $(tag) for versioning
        
         # Task 2: Publish Kubernetes manifests as build artifacts
         - task: PublishBuildArtifacts@1
           inputs:
             PathtoPublish: '$(System.DefaultWorkingDirectory)/k8s'
             ArtifactName: 'k8s'
             publishLocation: 'container